### PR TITLE
Update setup.py with valid bson package info

### PR DESCRIPTION
**Pull request by fish2000**
The `transmogrify` tool still totally works great – I only had to update the name and version of `bson` to the official MongoDB package, and it installed and works great as far as I can ascertain; I tried all the format types in a bunch of input/output combos with and without `--pretty`, and also `python setup.py test` (which, despite not having super encouraging output, did exit with zero). Yeah!

### CODE REVIEW

**Comment by fish2000** [comment]
@schwa – any interest?

**Comment by schwa** [comment]
Sure - will take a look.

**Comment by schwa** [comment]
Yup - looks good. thx.

**Comment by fish2000** [comment]
Sweet, glad that worked out! Salud.

**Pull request merged**
